on: 
  push:
    # only trigger on branches, not on tags
    branches: 
      - '**'

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    name: Scan ZAP website
    steps:
      - name: Check Docker is installed
        run: |
          docker --version
          docker info
          
      - name: ZAP Scan
        uses: zaproxy/zap-stable
        with:
          target: 'https://www.zaproxy.org/'